# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [
      #<nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ata_piix" "mptsas" "usb_storage" "usbhid" "floppy" ];
  boot.kernelModules = [ "kvm-intel" "tun" "virtio" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/eac025fd-9c63-4e9d-bb7a-bf236ae26030";
      fsType = "btrfs";
      options = [ "noatime" ];
    };

  swapDevices = [ ];

  nix.maxJobs = 4;
}
